spacy2conll = {
        'B-GPE': 'B-LOC', 'I-GPE': 'I-LOC',
        'B-PERSON': 'B-PER', 'I-PERSON': 'I-PER',
        'B-NORP': 'B-MISC', 'I-NORP': 'I-MISC',
        'B-CARDINAL': 'O', 'I-CARDINAL': 'O',
        'B-DATE': 'O', 'I-DATE': 'O', 
        'B-WORK_OF_ART': 'B-MISC', 'I-WORK_OF_ART': 'B-MISC',
        'B-TIME': 'O', 'I-TIME': 'O',
        'B-FAC': 'B-LOC', 'I-FAC': 'I-FAC', 
        'B-ORDINAL': 'O', 'I-ORDINAL': 'O', 
        'B-LANGUAGE': 'B-MISC', 'I-LANGUAGE': 'I-MISC',
        'B-PRODUCT': 'B-MISC', 'I-PRODUCT': 'I-MISC', 
        'B-QUANTITY': 'O', 'I-QUANTITY': 'O',
        'B-MONEY': 'O', 'I-MONEY': 'O', 
        'B-EVENT': 'B-MISC', 'I-EVENT': 'I-MISC', 
        'B-PERCENT': 'O', 'I-PERCENT': 'O',
        'B-LAW': 'B-MISC', 'I-LAW': 'I-MISC',
}